apiVersion: v1
kind: Service
metadata:
  name: nodejsk8s-service
  namespace: nodejsk8s
spec:
  type: LoadBalancer
  selector:
    app: nodejsk8s
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 30000